ipld/js-ipld-dag-pb

.gitignore, .travis.yml, README.md, package.json, src/dag-node.js, src/dag.proto.js, src/util.js, test/browser.js, test/dag-node-test.js
Ref https://github.com/ipfs/js-ipfs/pull/485
=> Async Crypto Endeavour

package.json
It is used [here](https://github.com/ipld/js-ipld-dag-pb/blob/master/src/resolver.js#L4).
=> bs58 is a normal dependecy

.gitignore, README.md, src/dag-node/create.js, test/dag-node-test.js
Basically, I ran into this because I mis-read the README and started putting in string data into `DAGNode.create`! If you do this, the current behaviour allows a number of odd/confusing scenarios, and it's not clear that you've done something wrong.
Currently, if a string is put in as the data, it will be accepted, and will work when put or gotten from IPFS, but it will break if you try and clone the DAGNode due to the line `dagNode.data.copy(data)` (js strings don't have a copy method).
Passing in string data seemed like a reasonable thing to do, but I felt converting the input data string to a buffer would be better than allowing the internal DAGNode data to be a string - I felt having two internal data representations would perhaps cause other unknown problems, however, I am open to …
=> Converting string input data to Buffer.

.eslintignore, .gitignore, .travis.yml, package.json, src/dag-node/create.js, src/dag-node/index.js, src/dag.proto, src/dag.proto.js, src/util.js, test/dag-node-test.js
=> fix: switch to protobufjs

src/resolver.js, test/resolver.spec.js
The isLink method (formerly isCID) appears [intended](https://github.com/ipld/js-ipld-dag-pb/blob/master/test/resolver.spec.js#L222) to identify paths specifically to link hashes (as opposed to paths to link name or size), but currently falls into the `true` case for paths to any truthy values. The tests pass because the non-valid CID case happens to check a path to an empty value.
Discussion [here](https://github.com/ipfs/js-ipfs/pull/1045#discussion_r159034560).
=> Fix false positives in isLink and update test

package.json
Instead of running lint and test before every commit, run it before
every push.
=> chore: change from pre-commit to pre-push validation

src/resolver.js, test/resolver.spec.js
IPLD shouldn't need to know about IPFS. Hence work directly with
the binary data instead of using an IPFS block.
This is part of https://github.com/ipld/interface-ipld-format/issues/21
BREAKING CHANGE: Everyone calling the functions of `resolve` need to
pass in the binary data instead of an IPFS block.
So if your input is an IPFS block, the code changes from
resolver.resolve(block, path, (err, result) => {…}
to
resolver.resolve(block.data, path, (err, result) => {…}
=> fix: use binary blobs directly

src/resolver.js, test/resolver.spec.js
In order to be similar to other IPLD formats, return the
full deserialized node if no path is given.
=> fix: return deserialized node if no path is given

src/dag-link/util.js, src/dag-node/addLink.js, src/util.js
this is part of ongoing effort to properly fix https://github.com/ipfs/js-ipfs/issues/1131
it replaces `link.constructor.name === 'DAGLink'` with a friendlier `link instanceof DAGLink`
=> replace constructor.name with instanceof so uglify can mangle and compress

src/dag-link/util.js, src/dag-node/addLink.js, src/util.js
Quoting @dignifiedquire: "there is a reason we don‘t use instanceof anywhere. It breaks for consumers using the library if they bundle a different set of code or the class."
Reverts ipld/js-ipld-dag-pb#58.
=> Revert "replace constructor.name with instanceof so uglify can mangle and compress"

package.json
According to the IPFS JS Guidelines all packages lower than version 1.0
should be prefixed with a tilde.
=> chore: changing all dependencies < 1.0 to `~`

package.json
This PR locks the `stable` dependecy to a working version, as the latest one breaks all the browser tests.
Fixes https://github.com/ipld/js-ipld-dag-pb/issues/65.
=> fix: lock stable dep

src/dag-link/index.js, test/dag-node-test.js
Changes the behaviour of `new DAGLink(...)` to default the link name to an empty string, otherwise you can get odd behaviour as detailed in ipld/js-ipld#125 where you fetch a `DAGNode` using a `CID` and it is returned with a different `CID` to the one you used to fetch it..
=> fix: Initialise the DAGLink name to empty string if a falsey value is passed

src/util.js, test/dag-node-test.js
BREAKING CHANGE: the first argument is now the serialized output NOT the dag node.
See https://github.com/ipld/interface-ipld-format/issues/32
=> fix: pass serialized blob to util.cid

.gitignore, src/resolver.js, test/resolver.spec.js
This is just a stab at fixing the _resolve links by name_ on dag-pb nodes. This PR is not finished (at all) but it shows what is missing.
Short story: go-ipfs and js-ipfs historically have supported the ability to do `jsipfs dag get CID/a` where a is a named link in a dag-pb.
So a dag-pb node like this.
```
{
Data: <some data>
Links: [
{
Name: a
Hash: b58...
Size: 1000
}
]
}
```
Should support resolving the link through name so that both `jsipfs dag get CID/a` and `jsipfs dag get CID/Links/0/Hash` are equivalent.
=> fix: add support for resolving links by name

src/dag-link/index.js
Here is a minimal change to support CIDs in a DAGLink. This allows things like traversing through from a dag-pb directory to a [git tree](https://github.com/ipfs-shipyard/ipld-explorer/issues/9#issuecomment-409295337)
We should really rename the property from `mutlihash` to `cid`, but that is breaking change. I'd be up for adding an additional cid property and deprecating `mutlihash` tho.
Fixes #79 
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
=> fix: support CIDs in DAGLink

package.json, src/dag-link/index.js, src/dag-node/addLink.js, src/dag-node/index.js, test/dag-link-test.js, test/dag-node-test.js
I've been doing some profiling of js-ipfs and where there are large amounts of DAG operations being performed (importing all of npm to ipfs, for example) we spend about 1.8-2.5% of our time in the creation of this._json objects, even though they are not always used, so this PR makes them be
created when first requested.
It also passes the `this._json` object through `Object.freeze` because otherwise we expose a mutable object to the world - it seems odd that we've taken pains to ensure that the properties of a DAGNode/DAGLink are immutable, then expose objects whose properties are not immutable.
Finally it makes more use of the `cids` module to parse CIDs from multihashes as the `cids` module respects CIDv1 versions/codecs if present whereas the `multihashes` module does not and is only …
=> perf: make this._json calculation lazy

src/dag-link/index.js, src/dag-node/index.js, test/dag-node-test.js
Relaxes the constraints from ipld/js-ipld-dag-pb#81 a little as it's caused quite a lot of tests to break.
We still have an immutable copy in the object but any objects returned will be mutable.
=> fix: allow mutating returned .toJSON value

src/resolver.js, test/resolver.spec.js
Resolve to the value of Name or Tsize, do not wrap in IPLD link object.
fixes #85
=> fix: resolve link Name or Tsize

src/util.js, test/util.spec.js
See #97 for context.  Essentially when we are deserializing a DAGNode from a buffer, the links should already be sorted so just new up a DAGNode object and return it.  Though we still have to calculate what the CID was that *may* have been used to load this DAGNode.  See ipld/js-ipld#173 for further discussion on that point.
=> perf: fixes #97 by not sorting DAGNode links when they are already sorted

README.md, src/dag-link/create.js, src/dag-link/index.js, src/dag-link/util.js, src/dag-node/addLink.js, src/dag-node/create.js, src/dag-node/index.js, src/dag-node/rmLink.js, src/dag-node/util.js, src/resolver.js, src/util.js, test/dag-link-test.js, test/dag-node-test.js, test/resolver.spec.js
Follows on from https://github.com/ipld/js-ipld/issues/173#issuecomment-434408680
These properties are removed from the DAGNode class.
* `.multihash` is removed because they aren't multihashes any more
* `.cid` is removed to bring dag-pb in line with other ipld types
* `.serialized` is removed because storing data buffers and the serialized form uses too much memory - we can use the utils.serialize method to create the serialized form when we need it, which in this module is just during the tests
`.multihash` has also changed to `.cid` in the output of `DAGLink.toJSON` and `DAGNode.toJSON` because since CIDv1 they are not just multihashes any more; the multihash is contained within the CID.
=> BREAKING CHANGE: Remove .cid, .multihash and .serialized properties

src/util.js
This Buffer.from() call make Node.js copy and reinitialize a Buffer
object, and it is a minor bottleneck of js-ipfs.
Before:
https://upload.clinicjs.org/public/d577b4af6f5c92adea857561aef4b3590f0fab3c964b00acc06f4093d73ce6dc/52850.clinic-flame.html
After:
https://upload.clinicjs.org/public/4ba0640c671dd4a618e486e9010abe537d82bb4be5d5ca3464c72445c7a22cae/53064.clinic-flame.html
=> perf: remove unneeded Buffer.from() call during deserialize

src/dag-link/index.js, src/dag-node/util.js
Allocating two buffers for every comparison was quite expensive.
This commit replaces Buffer.compare with String.prototype.localeCompare.
Fixes https://github.com/ipld/js-ipld-dag-pb/issues/107
Fixes: #104
=> perf: memoize the Name buffer in DAGLink to avoid unneeded allocations

package.json
There are a lot of dependencies that are no longer needed.
Checked via:
dependency-check ./package.json --missing --no-dev
dependency-check ./package.json --unused --no-dev
dependency-check ./package.json --missing ./test/*
dependency-check ./package.json --unused ./test/*
=> chore: clean up dependencies

src/dag-node/addLink.js, test/dag-node-test.js
`DAGNode.Links` converts `DAGLink` objects into vanilla JS objects. `DAGNode.addLink` accepts vanilla JS objects as links but looks for different properties from the ones the return value of `DAGNode.Links` have (e.g. `.Hash` vs `.cid`, etc)..
This PR corrects the behaviour to look for those properties names and adds a test for the same.
=> fix: allow adding links from DAGNode.Links

src/dag-link/util.js, test/dag-node-test.js
At some point in the distant past we supported a `.Size` property for `DAGLink`s so this PR adds that back in.
Also reorders the properties so the most recent (hopefully the most common) are first.
=> fix: support .Size property

src/dag-node/addNamedLink.js, test/resolver.spec.js
Prior to this change, named links didn't return the CID they are
pointing to, but the DAGLink. This made proper named links traversal
as it is done by UnixFSv1 impossible.
Thanks @alanshaw for finding and providing a solution to this bug.
=> fix: named links should return the CID

src/dag-node/addNamedLink.js
The code was wrong, it didn't actually use the keys of the object.
This also broke things in Browser environments.
Fixes https://github.com/ipfs/js-ipfs/issues/2090.
=> fix: actually use object keys

package.json, test/browser.js, test/dag-node-test.js, test/node.js
As we are moving from callbacks to async/await, it makes sense to
remove all occurrences of the async module.
=> chore: remove dependency on async

README.md, src/dag-node/dagNode.js, src/dag-node/toDagLink.js, src/serialize.js, src/util.js, test/dag-node-test.js, tools/pb-cross-language.go
2 bugs I discovered while trying to write my zip archive format for non-trivial portable test fixture data (i.e. my JS version of https://github.com/rvagg/go-ds-zipcar wasn't giving me the same CIDs).
1. `DAGNode` used to be immutable, `addLink()` and `rmLink()` would return new nodes on their callbacks. The current incarnation, since #141, mutates the current node, this means that `node._serializedSize` is incorrect upon either mutation operation. To fix this I've reset the cached sizing data and it's lazily re-calculated when you call `node.size` (as it is if you call the constructor without `serializedSize`).
2. `DAGNode#toDAGLink()` uses _serialized node size_ rather than _node size_ to create the new link, this is not how the Go implementation does it. That happened in #127 and I …
=> fix: serialization portability problems and size calculation bug

src/dag-link/dagLink.js
The polyfill is big, we can simulate it by throwing an Error and it doesn't work under React Native.
=> fix: remove use of assert module

package.json, src/dag-node/sortLinks.js, test/dag-node-test.js
Sorting is not stable on Node 10, adds a test that exposes the bug and reinstates the `stable` module to fix it.
Reverts 3048e3ea76a71f779193f6a24a5ed874d911b562
=> fix: revert stable module removal

package.json, src/dag-link/dagLink.js, src/dag-node/addLink.js, src/dag-node/dagNode.js, src/dag-node/rmLink.js, src/dag-node/sortLinks.js, src/serialize.js, test/dag-link-test.js, test/dag-node-test.js, test/mod.spec.js, test/resolver.spec.js, test/util.spec.js
This pull request attempts to add pure Data Model API interop (as per #173) in a backwards compatible way. High level overview of the changes are:
- Getters / Setters are replaced by non-writable public properties.
- Some internal ops that add / remove links do mutate arrays in place instead of swapping arrays (due to introduce non-writable constraint).
- serialization code now handles ArrayBuffer and TypedArray for `node.Data`.
Only visible change is that `node.Links` no longer returns links mapped to pure data, but rather `DAGLink` instances. However it should not matter in practice because those were made to behave just like pure data would. Although tests had to be change to use `.containSubset` instead of `.eql` because later fails when prototype chain is different.
=> Backwards compatible pure data model API

src/index.js, src/types.d.ts
If we require a JS class `Foo`, then export it as a property of an object,
ts thinks we are exporting `typeof Foo` rather than the `Foo` constructor.
At runtime `typeof` gets erased so ts gets upset by things like:
```js
const { DAGNode } = require('ipld-dag-pb')
if (bar instanceof DAGNode) {
// ...
}
```
..because as far as ts is concerned, `DAGNode` is actually `typeof DAGNode`
and `typeof DAGNode` has been erased since it's a `typeof` so `ipld-dag-pb`
does not export a property called `DAGNode` and kaboom.
The change here is to use the `types.d.ts` to define the `typeof` we are
exporting-but-not-really-exporting-since-it-gets-erased, use a `@typedef`
in the index file to actually export the type for use elsewhere, then rename
the `require`'d DAGNode/DAGLink classes to stop them …
=> fix: types again
